/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as timelockSol from "./Timelock.sol";
export { GovernorContract__factory } from "./GovernorContract__factory";
