/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as timelockSol from "./Timelock.sol";
export type { timelockSol };
export type { GovernorContract } from "./GovernorContract";
